services:
  postgres:
    image: 'postgres'
    network_mode: bridge
    container_name: postgres-container
    environment:
      - 'POSTGRES_DB=kmanager'
      - 'POSTGRES_PASSWORD=postgres'
      - 'POSTGRES_USER=postgres'
    labels:
      - "org.springframework.boot.service-connection=postgres"
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
  pgadmin:
    image: dpage/pgadmin4
    network_mode: bridge
    container_name: pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@admin.com
      - PGADMIN_DEFAULT_PASSWORD=admin
    ports:
      - "8181:80"
    depends_on:
      - postgres
  redis:
    image: redis
    network_mode: bridge
    container_name: redis
    command: redis-server
    ports:
      - "6379:6379"
volumes:
  pgdata: